### ISSUE TITLE
Unused Functions

### ISSUE THREAD

**Issue by lemmi** [gogs/git#29]
https://github.com/dominikh/go-tools/unused yields:

>[repo_history_handlers.go:7:6](https://github.com/gogits/git/blob/master/repo_history_handlers.go#L7-L9): func commitRootComparator is unused (U1000)
>[repo_object.go:91:25](https://github.com/gogits/git/blob/master/repo_object.go#L91-L98): func (*Repository).objectType is unused (U1000)
>[tree.go:36:16](https://github.com/gogits/git/blob/master/tree.go#L36-L39): func (*Tree).walk is unused (U1000)
>[tree.go:41:16](https://github.com/gogits/git/blob/master/tree.go#L41-L67): func (*Tree)._walk is unused (U1000)
>[tree_entry.go:63:2](https://github.com/gogits/git/blob/master/tree_entry.go#L63): field commited is unused (U1000)

Some of them look like they should be public, especially `func (*Tree).walk`. I always wondered what the `TreeWalkCallback` was for...

**Comment by Unknwon** [comment]
Hmm... unused maybe caused by several code refactoring rounds.
